@startuml
left to right direction
actor "Generic"


rectangle System{
	Generic -down-> (Register)
	Generic -down-> (Login)
	Generic -down-> (Forgot password)
	Generic -down-> (Display Event)
	Generic -down-> (Display Package)
	Generic -down-> (Display Treatment)
	Generic -down-> (Display Product)
	Generic -down-> (Display Comment)
}
@enduml