@startuml
left to right direction
actor "Consumer"


rectangle System{
	Consumer ->  (Login consumer)
	Consumer -> (Display/Add/Delete Booking)
	(Display/Add/Delete Booking) ..> (Login consumer): <<include>>
	Consumer -> (Display/Update Consumer)
	(Display/Update Consumer) ..> (Login consumer): <<include>>
	Consumer -> (Display Gift)
	(Display Gift) ..> (Login consumer): <<include>>
	Consumer -> (Add GiveProduct)
	(Add GiveProduct) ..> (Login consumer): <<include>>
	Consumer -> (Display/Add Order)
	(Display/Add Order) ..> (Login consumer): <<include>>
	Consumer -> (Display/Add/Update/Delete Service Comment)
	(Display/Add/Update/Delete Service Comment) ..> (Login consumer): <<include>>
}
@enduml